common: &common
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5

development:
  <<: *common
  database: wizard_app_development
  username: ubuntu
  password: password

test:
  <<: *common
  database: wizard_app_test
  username: ubuntu
  password: password

# production:
#   <<: *default
#   database: db/production.sqlite3
